### ISSUE TITLE
Backpack has no storage slots

### ISSUE THREAD

**Issue by Alatarius** [Vapok/AdventureBackpacks#31]
**Describe the bug**
Backpack has no storage space

**To Reproduce**
Craft backpack, open backpack inventory

**Expected behavior**
To have slots for backpack to put things in

**Screenshots**
screenshot attached

**Mod List (please list your mods that are being used):**
Player Log attached

**Additional context**

![Untitled](https://user-images.githubusercontent.com/101660302/215646883-f15aa74f-ef37-4e51-b2a7-70a076962dce.png)
[Player.log](https://github.com/Vapok/AdventureBackpacks/files/10542051/Player.log)

**Comment by Vapok** [comment]
I would try to equip and unequip again, or check your config and make sure you haven't completely hosed the config.  Everything about storage is 100% configurable in the config.

**Comment by Vapok** [comment]
So, I was able to actually reproduce this.   And I can't explain it, but on initial Valheim load, if the Explorer's Wisppack Level 1 is the first thing equipped, using default config, it'll show an empty inventory.  Unless one of the following occur:

1) You equip a different bag, show inventory, then equip Wisppack Level 1, and it'll show just fine.
2) Change Level 1 Wisppack from a 4x4 inventory configuration to any other non-square amount.

This might be a game bug.  The issue seems to not be present once the backpack has a non-square layout.  Try changing the Inventory Size on the Level 1 to be 5 width and 3 height, and you won't be able to reproduce the issue.

**Comment by Vapok** [comment]
I have relegated myself to the fact that I can't fix this.  It works perfectly as long as the 4x4 grid is not the first grid opened. No idea why.  As a result, I have "fixed" this in 1.6.3 by making the default inventory size on the Level 1 Wisspack 8x2 instead of 4x4.
