### ISSUE TITLE
Show cape instead of backpack

### ISSUE THREAD

**Issue by OctoberJemini** [Vapok/AdventureBackpacks#95]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to see the standard cape instead of the backpack.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Vapok** [comment]
This is from the FAQ on Discord:

**Can you make backpacks utilize the utility slot instead of shoulder slot? I want to wear a cape and have access to the backpack!**

From a role-playing aspect, I think requests like this are simply asking for things like "I want to utilize all the positive benefits without negative consequences." As an author, but mostly as a player, the backpacks are too good to not have to give up something. The ability to wear a cape is the trade-off decision that has to be made. It's one of the reasons why I made capes one of the ingredients, and don't, right off the bat, give the benefit of the cape to the backpack without an upgrade.

There's always some trade-off, some compromise that is made when making gearing choices. That was and still is my primary goal with these packs, to provide a fun adventure, while still forcing the player to make decisions on how they want to gear and/or look.

If wearing a cape is that important, then they can choose to wear a cape. It doesn't make sense for these to go into a random utility slot when backpacks are worn on the shoulders. Unfortunately, I have spent 1 too many decades playing RP games and I value a good trade-off system.

But I do recognize that I ask the player to make a choice: Capes or Backpacks. And I think it's a fair choice. I understand the importance of capes from a functional perspective, which is why each backpack is designed to eventually provide the effects of the cape that is used to make it.

I realize that this opinion from the author, might not suit everyone's needs, and if it turns out that's the deal breaker, well, I appreciate folks trying it out, and hope they find what they are looking for.

**Comment by OctoberJemini** [comment]
Entirely fair and understandable. Thank you for taking the time to write a response; that is very much appreciated.
